<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Model;

use DealerGoogleTimeZone\Model\Base\DealerGoogletimezone as BaseDealerGoogletimezone;

/**
 * Class DealerGoogletimezone
 * @package DealerGoogleTimeZone\Model
 */
class DealerGoogletimezone extends BaseDealerGoogletimezone
{
}
