<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Action;

use DealerGoogleTimeZone\Action\Base\DealerGoogletimezoneAction as  BaseDealerGoogletimezoneAction;

/**
 * Class DealerGoogletimezoneAction
 * @package DealerGoogleTimeZone\Action
 */
class DealerGoogletimezoneAction extends BaseDealerGoogletimezoneAction
{
}
