<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Form\Type;

use DealerGoogleTimeZone\Form\Type\Base\DealerGoogletimezoneIdType as BaseDealerGoogletimezoneIdType;

/**
 * Class DealerGoogletimezone
 * @package DealerGoogleTimeZone\Form
 */
class DealerGoogletimezoneIdType extends BaseDealerGoogletimezoneIdType
{
}
