<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone;

use Thelia\Module\BaseModule;
use Propel\Runtime\Connection\ConnectionInterface;
use Thelia\Install\Database;
use Thelia\Model\Config;
use Thelia\Model\ConfigQuery;

/**
 * Class DealerGoogleTimeZone
 * @package DealerGoogleTimeZone
 */
class DealerGoogleTimeZone extends BaseModule
{
    const MESSAGE_DOMAIN = "dealergoogletimezone";
    const ROUTER = "router.dealergoogletimezone";
    const RESOURCES_GOOGLETIMEZONE = "admin.dealer.googletimezone";

    public function postActivation(ConnectionInterface $con = null)
    {
        // Setup some default values
        if (!self::getConfigValue('is_initialized', false)) {
            self::setConfigValue('googletimezoneapi_key', '');

            $database = new Database($con);
            $database->insertSql(null, [__DIR__ . "/Config/create.sql", __DIR__ . "/Config/insert.sql"]);

            self::setConfigValue('is_initialized', true);
        }
    }
}
