<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Event\Module\Base;

/**
 * Class DealerGoogleTimeZoneEvents
 * @package DealerGoogleTimeZone\Event\Module\Base
 * @author TheliaStudio
 */
class DealerGoogleTimeZoneEvents
{
    const DEALER_GOOGLETIMEZONE_CREATE = "action.dealer_googletimezone.create";
    const DEALER_GOOGLETIMEZONE_UPDATE = "action.dealer_googletimezone.update";
    const DEALER_GOOGLETIMEZONE_DELETE = "action.dealer_googletimezone.delete";
}
