<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Event;

use DealerGoogleTimeZone\Event\Base\DealerGoogletimezoneEvents as BaseDealerGoogletimezoneEvents;

/**
 * Class DealerGoogletimezoneEvents
 * @package DealerGoogleTimeZone\Event
 */
class DealerGoogletimezoneEvents extends BaseDealerGoogletimezoneEvents
{
}
