<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Event;

use DealerGoogleTimeZone\Event\Base\DealerGoogletimezoneEvent as BaseDealerGoogletimezoneEvent;

/**
 * Class DealerGoogletimezoneEvent
 * @package DealerGoogleTimeZone\Event
 */
class DealerGoogletimezoneEvent extends BaseDealerGoogletimezoneEvent
{
}
