<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Form\Base;

use DealerGoogleTimeZone\Form\DealerGoogletimezoneCreateForm as ChildDealerGoogletimezoneCreateForm;
use DealerGoogleTimeZone\Form\Type\DealerGoogletimezoneIdType;

/**
 * Class DealerGoogletimezoneForm
 * @package DealerGoogleTimeZone\Form
 * @author TheliaStudio
 */
class DealerGoogletimezoneUpdateForm extends ChildDealerGoogletimezoneCreateForm
{
    const FORM_NAME = "dealer_googletimezone_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", DealerGoogletimezoneIdType::TYPE_NAME)
        ;
    }
}
