<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Form\Base;

use DealerGoogleTimeZone\DealerGoogleTimeZone;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;
use DealerGoogleTimeZone\Model\DealerGoogletimezoneQuery;


/**
 * Class DealerGoogletimezoneCreateForm
 * @package DealerGoogleTimeZone\Form\Base
 * @author TheliaStudio
 */
class DealerGoogletimezoneCreateForm extends BaseForm
{
    const FORM_NAME = "dealer_googletimezone_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addDealerIdField($translationKeys, $fieldsIdKeys);
        $this->addTimezoneField($translationKeys, $fieldsIdKeys);
    }

    protected function addDealerIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("dealer_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("dealer_id", $translationKeys), [], DealerGoogleTimeZone::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("dealer_id", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addTimezoneField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("timezone", "text", array(
            "label" => $this->translator->trans($this->readKey("timezone", $translationKeys), [], DealerGoogleTimeZone::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("timezone", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "dealer_id" => "dealer_googletimezone_dealer_id",
            "timezone" => "dealer_googletimezone_timezone",
        );
    }
}
