<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Loop;

use DealerGoogleTimeZone\Loop\Base\DealerGoogletimezone as BaseDealerGoogletimezoneLoop;

/**
 * Class DealerGoogletimezone
 * @package DealerGoogleTimeZone\Loop
 */
class DealerGoogletimezone extends BaseDealerGoogletimezoneLoop
{
    /**
     * You may now add your own logic
     */
}
