<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Form;

use DealerGoogleTimeZone\Form\Base\DealerGoogletimezoneUpdateForm as BaseDealerGoogletimezoneUpdateForm;

/**
 * Class DealerGoogletimezoneUpdateForm
 * @package DealerGoogleTimeZone\Form
 */
class DealerGoogletimezoneUpdateForm extends BaseDealerGoogletimezoneUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "dealer_id" => "dealer_id",
            "timezone" => "timezone",
        );
    }
}
