<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Form;

use DealerGoogleTimeZone\Form\Base\DealerGoogletimezoneCreateForm as BaseDealerGoogletimezoneCreateForm;

/**
 * Class DealerGoogletimezoneCreateForm
 * @package DealerGoogleTimeZone\Form
 */
class DealerGoogletimezoneCreateForm extends BaseDealerGoogletimezoneCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "dealer_id" => "Dealer id",
            "timezone" => "Timezone",
        );
    }
}
