<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Event\Module;

use DealerGoogleTimeZone\Event\Module\Base\DealerGoogleTimeZoneEvents as BaseDealerGoogleTimeZoneEvents;

/**
 * Class DealerGoogleTimeZoneEvents
 * @package DealerGoogleTimeZone\Event\Module
 * @author TheliaStudio
 */
class DealerGoogleTimeZoneEvents extends BaseDealerGoogleTimeZoneEvents
{
}
