<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Controller\Base;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Tools\URL;
use DealerGoogleTimeZone\Event\DealerGoogletimezoneEvent;
use DealerGoogleTimeZone\Event\DealerGoogletimezoneEvents;
use DealerGoogleTimeZone\Model\DealerGoogletimezoneQuery;

/**
 * Class DealerGoogletimezoneController
 * @package DealerGoogleTimeZone\Controller\Base
 * @author TheliaStudio
 */
class DealerGoogletimezoneController extends AbstractCrudController
{
    public function __construct()
    {
        parent::__construct(
            "dealer_googletimezone",
            "id",
            "order",
            AdminResources::MODULE,
            DealerGoogletimezoneEvents::CREATE,
            DealerGoogletimezoneEvents::UPDATE,
            DealerGoogletimezoneEvents::DELETE,
            null,
            null,
            "DealerGoogleTimeZone"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm()
    {
        return $this->createForm("dealer_googletimezone.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array())
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("dealer_googletimezone.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm($object)
    {
        $data = array(
            "id" => $object->getId(),
            "dealer_id" => $object->getDealerId(),
            "timezone" => $object->getTimezone(),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new DealerGoogletimezoneEvent();

        $event->setDealerId($formData["dealer_id"]);
        $event->setTimezone($formData["timezone"]);

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new DealerGoogletimezoneEvent();

        $event->setId($formData["id"]);
        $event->setDealerId($formData["dealer_id"]);
        $event->setTimezone($formData["timezone"]);

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent()
    {
        $event = new DealerGoogletimezoneEvent();

        $event->setId($this->getRequest()->request->get("dealer_googletimezone_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event)
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getDealerGoogletimezone();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return DealerGoogletimezoneQuery::create()
            ->findPk($this->getRequest()->query->get("dealer_googletimezone_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object)
    {
        return '';
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("dealer-googletimezones");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->getParserContext()
            ->set(
                "dealer_googletimezone_id",
                $this->getRequest()->query->get("dealer_googletimezone_id")
            )
        ;

        return $this->render("dealer-googletimezone-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToEditionTemplate()
    {
        $id = $this->getRequest()->query->get("dealer_googletimezone_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/DealerGoogleTimeZone/dealer_googletimezone/edit",
                [
                    "dealer_googletimezone_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToListTemplate()
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/DealerGoogleTimeZone/dealer_googletimezone")
        );
    }
}
