<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Event\Base;

use Thelia\Core\Event\ActionEvent;
use DealerGoogleTimeZone\Model\DealerGoogletimezone;

/**
* Class DealerGoogletimezoneEvent
* @package DealerGoogleTimeZone\Event\Base
* @author TheliaStudio
*/
class DealerGoogletimezoneEvent extends ActionEvent
{
    protected $id;
    protected $dealerId;
    protected $timezone;
    protected $dealerGoogletimezone;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getDealerId()
    {
        return $this->dealerId;
    }

    public function setDealerId($dealerId)
    {
        $this->dealerId = $dealerId;

        return $this;
    }

    public function getTimezone()
    {
        return $this->timezone;
    }

    public function setTimezone($timezone)
    {
        $this->timezone = $timezone;

        return $this;
    }

    public function getDealerGoogletimezone()
    {
        return $this->dealerGoogletimezone;
    }

    public function setDealerGoogletimezone(DealerGoogletimezone $dealerGoogletimezone)
    {
        $this->dealerGoogletimezone = $dealerGoogletimezone;

        return $this;
    }
}
