<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Event\Base;

use DealerGoogleTimeZone\Event\Module\DealerGoogleTimeZoneEvents as ChildDealerGoogleTimeZoneEvents;

/*
 * Class DealerGoogletimezoneEvents
 * @package DealerGoogleTimeZone\Event\Base
 * @author TheliaStudio
 */
class DealerGoogletimezoneEvents
{
    const CREATE = ChildDealerGoogleTimeZoneEvents::DEALER_GOOGLETIMEZONE_CREATE;
    const UPDATE = ChildDealerGoogleTimeZoneEvents::DEALER_GOOGLETIMEZONE_UPDATE;
    const DELETE = ChildDealerGoogleTimeZoneEvents::DEALER_GOOGLETIMEZONE_DELETE;
}
