<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Controller;

use DealerGoogleTimeZone\Controller\Base\DealerGoogletimezoneController as BaseDealerGoogletimezoneController;

/**
 * Class DealerGoogletimezoneController
 * @package DealerGoogleTimeZone\Controller
 */
class DealerGoogletimezoneController extends BaseDealerGoogletimezoneController
{
}
