<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DealerGoogleTimeZone\Action\Base;

use DealerGoogleTimeZone\Model\Map\DealerGoogletimezoneTableMap;
use DealerGoogleTimeZone\Event\DealerGoogletimezoneEvent;
use DealerGoogleTimeZone\Event\DealerGoogletimezoneEvents;
use DealerGoogleTimeZone\Model\DealerGoogletimezoneQuery;
use DealerGoogleTimeZone\Model\DealerGoogletimezone;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class DealerGoogletimezoneAction
 * @package DealerGoogleTimeZone\Action
 * @author TheliaStudio
 */
class DealerGoogletimezoneAction extends BaseAction implements EventSubscriberInterface
{
    public function create(DealerGoogletimezoneEvent $event)
    {
        $this->createOrUpdate($event, new DealerGoogletimezone());
    }

    public function update(DealerGoogletimezoneEvent $event)
    {
        $model = $this->getDealerGoogletimezone($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(DealerGoogletimezoneEvent $event)
    {
        $this->getDealerGoogletimezone($event)->delete();
    }

    protected function createOrUpdate(DealerGoogletimezoneEvent $event, DealerGoogletimezone $model)
    {
        $con = Propel::getConnection(DealerGoogletimezoneTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $dealerId = $event->getDealerId()) {
                $model->setDealerId($dealerId);
            }

            if (null !== $timezone = $event->getTimezone()) {
                $model->setTimezone($timezone);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setDealerGoogletimezone($model);
    }

    protected function getDealerGoogletimezone(DealerGoogletimezoneEvent $event)
    {
        $model = DealerGoogletimezoneQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'dealer_googletimezone' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            DealerGoogletimezoneEvents::CREATE => array("create", 128),
            DealerGoogletimezoneEvents::UPDATE => array("update", 128),
            DealerGoogletimezoneEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".dealer_googletimezone_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".dealer_googletimezone_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".dealer_googletimezone_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".dealer_googletimezone_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
